runtime: nodejs10
service: default
env: standard
instance_class: F1
handlers:
  - url: /(.*\.(svg|gif|media|json|ico|eot|ttf|woff|woff2|png|jpg|css|js))$
    static_files: build/\1
    upload: build/(.*)
  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html
